[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "base-uri 'self'; block-all-mixed-content; child-src 'self'; connect-src 'self'; default-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-ancestors 'none'; img-src 'self' data: https://ik.imagekit.io; object-src 'none'; script-src 'self' 'nonce-999999999' 'unsafe-inline'; script-src-elem 'self' 'nonce-999999999'; style-src 'self' https://fonts.googleapis.com 'nonce-999999999' 'unsafe-inline'; upgrade-insecure-requests;"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "accelerometer=(),autoplay=(),camera=(),display-capture=(),encrypted-media=(),fullscreen=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),screen-wake-lock=(),sync-xhr=(self),usb=(),web-share=(),xr-spatial-tracking=()"

[[edge_functions]]
  function = "include"
  path = "/"

[[edge_functions]]
  function = "include"
  path = "/index.html"

[[redirects]]
  from = "*"
  to = "404.html"
  status = 404