[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "block-all-mixed-content; child-src 'self'; connect-src 'self'; default-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-ancestors 'none'; img-src 'self' data: https://ik.imagekit.io; object-src 'none'; script-src 'self' 'nonce-999999999' 'unsafe-inline'; script-src-elem 'self'; style-src 'self' https://fonts.googleapis.com 'nonce-999999999' 'unsafe-inline'; upgrade-insecure-requests;"

[[edge_functions]]
  function = "include"
  path = "/*"